import type {
  BriefCard,
  Company,
  MemoryItem,
  Person,
  Project,
  SearchResult,
  TimelineEvent,
} from "./types";

export const COMPANIES: Company[] = [
  {
    id: "pln",
    name: "PLN",
    sector: "Energy & Utilities",
    health: 92,
    healthLabel: "Strong",
    revenue: "Rp 420B pipeline",
    contacts: 12,
    activeProjects: 2,
    summary:
      "Grid modernization phase 2 in active negotiation. Communication volume up 35% this week.",
  },
  {
    id: "mayora",
    name: "Mayora",
    sector: "FMCG & Distribution",
    health: 88,
    healthLabel: "Growing",
    revenue: "Rp 85M PO issued",
    contacts: 8,
    activeProjects: 1,
    summary: "Purchase order PO-8821 for distribution analytics module.",
  },
  {
    id: "telkom",
    name: "Telkom",
    sector: "Telecommunications",
    health: 84,
    healthLabel: "Stable",
    revenue: "Rp 120M renewal",
    contacts: 6,
    activeProjects: 1,
    summary: "Q3 enterprise review meeting scheduled. Renewal discussion ongoing.",
  },
  {
    id: "abc",
    name: "PT ABC Construction",
    sector: "Construction",
    health: 71,
    healthLabel: "Watch",
    revenue: "Rp 1.2M outstanding",
    contacts: 4,
    activeProjects: 1,
    summary: "Invoice INV-203 due tomorrow. Payment confirmation pending.",
  },
];

export const PEOPLE: Person[] = [
  {
    id: "ary",
    name: "Ary Wibowo",
    role: "Founder & CEO",
    companyId: "ida",
    email: "ary@ida.id",
    engagements: 47,
    lastActive: "Just now",
    summary: "Executive oversight across PLN, Mayora, and stalled Project Alpha.",
  },
  {
    id: "budi",
    name: "Budi Santoso",
    role: "Account Director",
    companyId: "pln",
    email: "budi.santoso@pln.co.id",
    engagements: 18,
    lastActive: "8 min ago",
    summary: "Leading PLN grid modernization conversations and Q3 planning.",
  },
  {
    id: "rina",
    name: "Rina Wijaya",
    role: "Finance Lead",
    companyId: "abc",
    email: "finance@abcconstruction.co.id",
    engagements: 6,
    lastActive: "2 hours ago",
    summary: "Owns invoice INV-203 and commercial follow-ups.",
  },
  {
    id: "david",
    name: "David Chen",
    role: "Program Manager",
    companyId: "ida",
    email: "david@ida.id",
    engagements: 14,
    lastActive: "Yesterday",
    summary: "Accountable for Project Alpha delivery and stakeholder updates.",
  },
];

export const PROJECTS: Project[] = [
  {
    id: "alpha",
    name: "Project Alpha",
    companyId: "abc",
    ownerId: "david",
    status: "stalled",
    budget: "Rp 45M",
    progress: 42,
    summary: "No update for 9 days. Three deliverables pending executive decision.",
    updatedAt: "9 days ago",
  },
  {
    id: "pln-grid",
    name: "PLN Grid Modernization",
    companyId: "pln",
    ownerId: "budi",
    status: "on-track",
    budget: "Rp 120M",
    progress: 68,
    summary: "Phase 2 proposal timeline confirmed. Technical review next week.",
    updatedAt: "Today",
  },
  {
    id: "mayora-analytics",
    name: "Mayora Distribution Analytics",
    companyId: "mayora",
    ownerId: "ary",
    status: "on-track",
    budget: "Rp 32M",
    progress: 55,
    summary: "PO-8821 received. Kickoff and data integration planning in progress.",
    updatedAt: "Yesterday",
  },
];

export const BRIEF_CARDS: BriefCard[] = [
  {
    id: "c1",
    tone: "critical",
    title: "Project Alpha stalled — 9 days without update",
    description: "Three deliverables blocked. Stakeholder complaint escalated.",
    entityType: "project",
    entityId: "alpha",
    metric: "Rp 45M at risk",
  },
  {
    id: "c2",
    tone: "critical",
    title: "Invoice INV-203 due tomorrow",
    description: "PT ABC Construction — Rp 1.2M payment confirmation needed.",
    entityType: "company",
    entityId: "abc",
    metric: "Due in 24h",
  },
  {
    id: "o1",
    tone: "opportunity",
    title: "PLN grid modernization advancing",
    description: "Communication +35% in 24h. Phase 2 proposal window open.",
    entityType: "company",
    entityId: "pln",
    metric: "Health 92",
  },
  {
    id: "o2",
    tone: "opportunity",
    title: "Mayora PO-8821 signed",
    description: "Distribution analytics module — fast-track kickoff recommended.",
    entityType: "company",
    entityId: "mayora",
    metric: "Rp 32M",
  },
  {
    id: "h1",
    tone: "health",
    title: "PLN customer health strong",
    description: "12 active threads, 4 meetings this month, renewal on track.",
    entityType: "company",
    entityId: "pln",
    metric: "92%",
  },
  {
    id: "h2",
    tone: "health",
    title: "Organization health score",
    description: "128 active connections, 24 updates today across the org graph.",
    metric: "92%",
  },
  {
    id: "r1",
    tone: "risk",
    title: "ABC payment delay risk",
    description: "Outstanding invoice may impact Project Alpha cash flow.",
    entityType: "company",
    entityId: "abc",
  },
  {
    id: "r2",
    tone: "risk",
    title: "Resource contention on Q3 reviews",
    description: "Telkom and PLN reviews overlap — capacity conflict possible.",
    entityType: "company",
    entityId: "telkom",
  },
  {
    id: "a1",
    tone: "action",
    title: "Schedule executive call with PLN",
    description: "Confirm phase 2 timeline before board review Friday.",
    entityType: "person",
    entityId: "budi",
  },
  {
    id: "a2",
    tone: "action",
    title: "Unblock Project Alpha deliverables",
    description: "Assign decision owner and publish recovery plan to stakeholders.",
    entityType: "project",
    entityId: "alpha",
  },
];

export const TIMELINE: TimelineEvent[] = [
  {
    id: "t1",
    date: "Today, 10:20",
    title: "PLN Q3 planning thread",
    type: "communication",
    entityType: "company",
    entityId: "pln",
    summary: "18 new messages from Budi Santoso on grid modernization.",
  },
  {
    id: "t2",
    date: "Today, 09:00",
    title: "Executive sync — Project Alpha",
    type: "meeting",
    entityType: "project",
    entityId: "alpha",
    summary: "Review stalled deliverables and escalation path.",
  },
  {
    id: "t3",
    date: "Yesterday",
    title: "Mayora PO-8821 received",
    type: "commercial",
    entityType: "company",
    entityId: "mayora",
    summary: "Purchase order for distribution analytics module.",
  },
  {
    id: "t4",
    date: "Yesterday",
    title: "Approve Telkom review agenda",
    type: "decision",
    entityType: "company",
    entityId: "telkom",
    summary: "Q3 enterprise review scope confirmed.",
  },
  {
    id: "t5",
    date: "2 days ago",
    title: "Invoice INV-203 issued",
    type: "commercial",
    entityType: "company",
    entityId: "abc",
    summary: "Rp 1.2M from PT ABC Construction.",
  },
  {
    id: "t6",
    date: "3 days ago",
    title: "PLN technical workshop",
    type: "meeting",
    entityType: "company",
    entityId: "pln",
    summary: "Architecture review for phase 2 integration.",
  },
];

export const MEMORY_ITEMS: MemoryItem[] = [
  {
    id: "m1",
    tab: "communications",
    title: "RE: Q3 Planning — PLN Grid Modernization",
    subtitle: "Budi Santoso • 18 messages",
    date: "Today",
    entityType: "company",
    entityId: "pln",
  },
  {
    id: "m2",
    tab: "communications",
    title: "URGENT: Project Alpha status",
    subtitle: "David Chen • Internal",
    date: "Today",
    entityType: "project",
    entityId: "alpha",
  },
  {
    id: "m3",
    tab: "meetings",
    title: "Telkom Enterprise Review Q3",
    subtitle: "Calendar • 5 attendees",
    date: "Tomorrow",
    entityType: "company",
    entityId: "telkom",
  },
  {
    id: "m4",
    tab: "meetings",
    title: "PLN Technical Workshop recap",
    subtitle: "Notes captured • 3 action items",
    date: "3 days ago",
    entityType: "company",
    entityId: "pln",
  },
  {
    id: "m5",
    tab: "projects",
    title: "PLN Grid Modernization — Phase 2",
    subtitle: "68% complete • On track",
    date: "Today",
    entityType: "project",
    entityId: "pln-grid",
  },
  {
    id: "m6",
    tab: "projects",
    title: "Project Alpha recovery plan",
    subtitle: "Blocked • Needs decision",
    date: "9 days ago",
    entityType: "project",
    entityId: "alpha",
  },
  {
    id: "m7",
    tab: "commercial",
    title: "Invoice INV-203",
    subtitle: "PT ABC • Rp 1.2M",
    date: "Due tomorrow",
    entityType: "company",
    entityId: "abc",
  },
  {
    id: "m8",
    tab: "commercial",
    title: "Mayora PO-8821",
    subtitle: "Procurement • Signed",
    date: "Yesterday",
    entityType: "company",
    entityId: "mayora",
  },
  {
    id: "m9",
    tab: "decisions",
    title: "Approve Telkom Q3 agenda",
    subtitle: "Executive decision logged",
    date: "Yesterday",
    entityType: "company",
    entityId: "telkom",
  },
  {
    id: "m10",
    tab: "decisions",
    title: "Project Alpha escalation",
    subtitle: "Pending owner assignment",
    date: "Today",
    entityType: "project",
    entityId: "alpha",
  },
  {
    id: "m11",
    tab: "notes",
    title: "Investor demo narrative",
    subtitle: "Organization as one living system",
    date: "Today",
  },
  {
    id: "m12",
    tab: "notes",
    title: "PLN relationship strategy",
    subtitle: "Expand from pilot to enterprise-wide",
    date: "This week",
    entityType: "company",
    entityId: "pln",
  },
];

export const SEARCH_INDEX: SearchResult[] = [
  ...COMPANIES.map((c) => ({
    id: `s-${c.id}`,
    group: "Companies" as const,
    title: c.name,
    subtitle: `${c.sector} • Health ${c.health}`,
    entityType: "company" as const,
    entityId: c.id,
  })),
  ...PEOPLE.map((p) => ({
    id: `s-${p.id}`,
    group: "People" as const,
    title: p.name,
    subtitle: `${p.role} • ${p.email}`,
    entityType: "person" as const,
    entityId: p.id,
  })),
  ...PROJECTS.map((p) => ({
    id: `s-${p.id}`,
    group: "Projects" as const,
    title: p.name,
    subtitle: `${p.status} • ${p.budget}`,
    entityType: "project" as const,
    entityId: p.id,
  })),
  ...MEMORY_ITEMS.slice(0, 6).map((m) => ({
    id: `s-${m.id}`,
    group: "Memory" as const,
    title: m.title,
    subtitle: m.subtitle,
    entityType: "memory" as const,
    entityId: m.id,
  })),
  {
    id: "s-dec-1",
    group: "Decisions",
    title: "Approve Telkom Q3 agenda",
    subtitle: "Executive decision • Yesterday",
    entityType: "memory",
    entityId: "m9",
  },
];

export function getCompany(id: string) {
  return COMPANIES.find((c) => c.id === id);
}

export function getPerson(id: string) {
  return PEOPLE.find((p) => p.id === id);
}

export function getProject(id: string) {
  return PROJECTS.find((p) => p.id === id);
}